"use client"
import React, { useState, useEffect } from "react";
import { addReport, getReports } from "../_services/reports-service";
import { UserAuth  } from "../context/AuthContext.js";
import MapReport from './MapReport.js'
// page generated by chatgpt as a placeholder
export default function ReportPage() {
    // State variables for each input field
    const [title, setTitle] = useState("");
    const [text, setText] = useState("");
    const [date, setDate] = useState("");
    const [location, setLocation] = useState("");
    const [reports, setReports] = useState([]);
    const reportsList = [...reports]

    const { user } = UserAuth(); // Get the user from the auth hook

    // Handler to process the report submission

    const loadReports = async () => {
        const reports = await getReports(user.uid);
        console.log("Reports", reports);
        setReports(reports);
    }

    const handleSubmit = async (event) => {
        event.preventDefault();
    
        // Guard clause to ensure user is authenticated
        if (!user) {
            console.error('User is not authenticated.');
            return;
        }
    
        const report = {
            title: title,
            text: text,
            date: date,
            location: location,
        };
    
        try {
            console.log("Submitting report", report);
            console.log("User", user.uid);
            const reportId = await addReport(user.uid, report);
            console.log('Report added with ID:', reportId);
            setTitle("");
            setText("");
            setDate("");
            setLocation("");
        } catch (error) {
            console.error('Error submitting report:', error);
            // Handle the error appropriately in your UI
        }
    };

    useEffect(() => {
        if (typeof window !== 'undefined') {
            loadReports();
        }
    // eslint-disable-next-line react-hooks/exhaustive-deps
    }, [user]);

    

    return (
        <div className="bg-black">
            <h1>Submit a Report</h1>
            <form onSubmit={handleSubmit}>
                <div>
                    <label htmlFor="title">Title:</label>
                    <input
                        type="text"
                        id="title"
                        value={title}
                        onChange={(e) => setTitle(e.target.value)}
                        className="text-black"
                    />
                </div>
                <div>
                    <label htmlFor="text">Text:</label>
                    <textarea
                        id="text"
                        value={text}
                        onChange={(e) => setText(e.target.value)}
                        className="text-black"
                    />
                </div>
                <div>
                    <label htmlFor="date">Date:</label>
                    <input
                        type="date"
                        id="date"
                        value={date}
                        onChange={(e) => setDate(e.target.value)}
                        className="text-black"
                    />
                </div>
                <div>
                    <label htmlFor="location">Location:</label>
                    <input
                        type="text"
                        id="location"
                        value={location}
                        onChange={(e) => setLocation(e.target.value)}
                        className="text-black"
                    />
                </div>
                <button onSubmit={addReport} type="submit">Submit Report</button>
            </form>

            <div className="reportsContainer">
                {/* Display the reports here */}
                {/* fix this, pass props like the web dev 2 assignments */}
                {reportsList.map((report) => (
                    <div key={report.id}>
                        <h2>{report.title}</h2>
                        <p>{report.text}</p>
                        <p>{report.date}</p>
                        <p>{report.location}</p>
                    </div>
                ))}
            </div>
        </div>
    );
}
