"use client"
import React, { useState, useEffect } from "react";
import { addReport, getReports } from "./_services/reports-service.js";
import { UserAuth } from "../context/AuthContext.js";
import { LocationProvider } from './LocationContext';

import MapReport from "./MapReport.js";
import ReportPage from "./reportsList.js"
import ReportForm from './reportForm.js';
// page generated by chatgpt as a placeholder
export default function ReportPage() {
    // State variables for each input field
    const [title, setTitle] = useState("");
    const [text, setText] = useState("");
    const [date, setDate] = useState("");
    const [isPrivate, setIsPrivate] = useState(false); // Use boolean state for "use private"
    const [location, setLocation] = useState("");
    const [reports, setReports] = useState([]);

    const { user } = UserAuth(); // Get the user from the auth hook

    const handleAddReport = (event) => {
        setReports([...reports, event]);
    };

    const loadReports = async () => {
        if (typeof window !== 'undefined') {
            const reportsData = await getReports(user.uid);
            console.log("Reports", reportsData);
            setReports(reportsData);
        }
    };

    const handleSubmit = async (event) => {
        event.preventDefault();
    
        // Guard clause to ensure user is authenticated
        if (!user) {
            console.error('User is not authenticated.');
            return;
        }
    
        const report = {
            title: title,
            text: text,
            date: date,
            location: location,
            isPrivate: isPrivate // Use the state variable directly
        };
    
        try {
            const reportId = await addReport(user.uid, report);
            console.log('Report added with ID:', reportId);
            handleAddReport(report);
            setTitle("");
            setText("");
            setDate("");
            setLocation("");
        } catch (error) {
            console.error('Error submitting report:', error);
            // Handle the error appropriately in your UI
        }
    };

    useEffect(() => {
        if (user) {
            loadReports();
        }
        else{
            return;
        }
    }, [user, reports]);
    

export default function page() {
    return (
        <div className='bg-gray-900 w-full items-center p-20 m-auto flex flex-row'>
            <div className="bg-gray-800 py-4 px-4 rounded-md">
                <div>
                    <h1 className="text-2xl">Submit a Report</h1>
                </div>
                <div>
                    <form onSubmit={handleSubmit}>
                        {/* Other input fields */}
                        <div className="p-2 ">
                            <div>
                                <label htmlFor="isPublic">Use Client:</label>
                            </div>
                            <div>
                                <label htmlFor="title">Title:</label>
                            </div>
                            <div>
                                <input
                                    type="text"
                                    id="title"
                                    value={title}
                                    onChange={(e) => setTitle(e.target.value)}
                                    className="text-white input"
                                />
                            </div>
                        </div>
                        <div className="p-2">
                            <div>
                                <label htmlFor="text">Text:</label>
                            </div>
                            <div>
                                <textarea
                                    id="text"
                                    value={text}
                                    onChange={(e) => setText(e.target.value)}
                                    className="text-white textarea"
                                />
                            </div>
                        </div>
                        <div className="p-2">
                            <div>
                                <label htmlFor="date">Date:</label>
                            </div>
                            <div>
                                <input
                                    type="date"
                                    id="date"
                                    value={date}
                                    onChange={(e) => setDate(e.target.value)}
                                    className="text-white input"
                                />
                            </div>
                        </div>
                        <div className="p-2">
                            <div>
                                <label htmlFor="location">Location:</label>
                            </div>
                            <div>
                                <input
                                    type="text"
                                    id="location"
                                    value={location}
                                    onChange={(e) => setLocation(e.target.value)}
                                    className="text-white input"
                                />
                            </div>
                        </div>
                        <div className="p-2 ">
                            <div>
                                <label htmlFor="isPrivate">Use Private:</label>
                            </div>
                            <div>
                                <input
                                    type="checkbox"
                                    id="isPrivate"
                                    checked={isPrivate}
                                    onChange={(e) => setIsPrivate(e.target.checked)}
                                />
                            </div>
                        </div>
                        <button className="btn mt-2 ml-2" type="submit">Submit Report</button>
                    </form>
                </div>
            </div>

            <div className="reportsContainer">
                {/* Display the reports here */}
                {/* fix this, pass props like the web dev 2 assignments */}
                {reports.map((report) => (
                    <div key={report.id} className="p-3 bg-gray-800 rounded-md m-3">
                        <h2>{report.title}</h2>
                        <p>{report.text}</p>
                        <p>{report.date}</p>
                        <p>{report.location}</p>
                        <p>{report.isPrivate}</p>
                    </div>
                ))}
            </div>
        <LocationProvider>
        <div className="flex justify-between">
          <div className="w-full">
            <MapReport/>
          </div>
          <div className="w-2/5 h-full">
            <ReportForm/>
          </div>
        </div>
      </LocationProvider>
    );
}
